app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexMain.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
# from blog.views import Index

app_name = 'blog'

urlpatterns = [
    path("", views.Index.as_view(), name='list'),

    # 글 상세조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'),
    
    # 글 작성
    path("write/", views.Write.as_view(), name='write'), # views에 write 함수.

    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),

    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),

    # 댓글 작성
    path("detail/<int:pk>/comment/write/", views.commentWrite.as_view(), name='cm-write'),

    # 댓글 삭제
    path("detail/<int:pk>/comment/delete/", views.CommentDelete.as_view(), name='cm-delete'),

    # 해시태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='ht-write'),

    # 해시태그 삭제
    path("detail/<int:pk>/hashtag/delete", views.HashTagDelete.as_view(), name='ht-delete'),

    # 글 검색
    path("search/<str:q>/", views.PostSearch.as_view(), name='search'),

    # 카테고리 검색
    path("category/<str:slug>/", views.CategorySearch, name='category'),

]

# 여기에 정의하는 애들은 서버주소/blog에 정의가 되는 애들이다.

# 함수기반, 클래스기반 뷰의 표기 바업ㅂ이 다르다.
# 캡슐화, 상속 가능.

blog/models.py
# Create your models here.
from django.db import models
import os

# Create your models here.
# 데이터베이스가 테이블처럼 형태를 가지고 있다.

# 장고에서는 관계형 데이터베이스를 사용한다
# 테이블이나 엑셀 형태를 가지고 있는 것들.

# 장고 블로그를 만들 때 데이터베이스를 만들어야
# 된다고 하면,
# ORM? 데이터베이스를 구축해야 되는 걸 도와주는 것.
# 각각을 클래스로 만들면 알아서 대응되는 
# 테이블을 만들어준다.
# 1:1 대응하는 테이블을 디비에서 만들어준다.
# 이것을 장고의 Orm 기능이라고 한다.


# 클래스 하나가 테이블 하나를 나타낸다.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    # 생성된 시간만 저장을 한다.
    # 크리에이티드엣은 수정이 되면 안되는 시간 값.
    created_at = models.DateTimeField(auto_now_add=True)
    # 새로 세이브 될 때마다 그 시간을 저장을 해준다.
    updated_at = models.DateTimeField(auto_now=True)

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/images/%Y/%m/%d/', blank=True)

    category = models.ForeignKey('Category', blank=True, null=True, on_delete=models.SET_NULL)
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.CharField(max_length=128)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


# class HashTag(models.Model):
#     post = models.ForeignKey('Post', on_delete=models.CASCADE)
#     writer = models.CharField(max_length=128)
#     name = models.CharField(max_length=10)

#     def __str__(self):
#         return self.name

class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.CharField(max_length=128)
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'

blog/forms.py
# blog/forms.py

from django import forms
from .models import Post, Comment, HashTag


# 일반 Form: html에 있는 form 태그
# 유효성 검사를 위해서 form을 써준다. 
# modelform: model을 사용하는 form
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'head_image', 'file_upload']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'size': '30'})
        }


class HashTagForm(forms.ModelForm):

    class Meta:
        model = HashTag
        fields = ['name']   

blog/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from django.views import View 
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment, HashTag, Category # 같은 경로의 models에서 Post 가져옴.
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
# 블로그 안에 있는 views.py를 열었다.
# models - urls - views 순서로 하는 거에서 끝 단계까지 왔다.

'''
웹 요청을 받는다. url + method로 받는다.
요청을 처리하고 디비에서 필요한 값이 있다면 가져온다.
가져온 값을 가공, 정리해서 응답 형태로 만들어준다.
응답을 반환한다.
그 전에 urls에서 맵핑을 해주는게 우선이다.

fbv 함수 기반 뷰 - 얘가 우선 이해가 되어야 클래스 기반이 이해가 된다.
cbv 클래스 기반 뷰
'''

### post list - 일반 뷰
# 클래스로 동일하게 다시한 번 만들어보자.
# class Index(View):
#     def get(self, request):
#         # return HttpResponse('index page GET class')
        
#         # 디비에 접근해서 값을 가져와아 한다.
#         # 게시판에 글을 보여줘야되기 때문에 디비에서 값 조회
    
#         post_objs = Post.objects.all().order_by('-pk')
#         context = {
#             "posts": post_objs
#             # "posts": None
#         }

#         # 렌더의 정석적 인자값 3개
#         return render(request, 'blog/post_list.html', context)

### post list - 제네릭 뷰
# 일반 뷰 쪽으로 포스팅이 들어간다?
class Index(ListView):
    model = Post
    ordering = '-pk'
    # ordering = ['created_at']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context
    
def CategorySearch(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(request, 'blog/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        }
    )


# django 자체에 클래스 뷰 기능이 강력하고 편리하다.

# 많이 사용.
# model, template_name, context_object_name,
# paginate_by - 페이지를 어떻게 끊어줄 것인지.
# form_class, form_valid(), get_queryset()


# 어떤 함수를 만들 때, get, post 중 뭐가 필요한지를 제일 먼저 고민해야 한다.
class Write(LoginRequiredMixin,View): # 이미 로그인된 유저만 받아주겠다.
# class Write(View): # 이미 로그인된 유저만 받아주겠다.
    def get(self, request):
        form = PostForm()
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html', context)
        # 랜더 함수 안에는 html 풀 네임을 써준다.

    # 사용자에게 값을 받아노는 요청이기 때문에 request.POST를 해줘야 한다.
    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False) # 값이 변할 수 있음을 명시
            post.writer = request.user # 인증된 유저의 값을 writer로 받겠다
            post.save() 
            return redirect('blog:list')
        
        form.add_error(None, '폼이 유효하지 않습니다.')
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html')


class Update(View):
    def get(self, request, pk): # post_id
        post = Post.objects.get(pk = pk)
        form = PostForm(initial={'title': post.title, 'content': post.content})
        context = {
            'form': form,
            'post': post
        }
        return render(request, 'blog/post_edit.html', context)

    def post(self, request, pk):
        post = Post.objects.get(pk = pk)
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)

        form.add_error('유효하지 않은 폼.')
        context = {
            'form': form
        }
        return render(request, 'blog/form_error.html', context)


class Delete(View):
    # get은 필요없다. 별도 삭제 페이지가 없기 때문에.
    def post(self, request, pk):
        post = Post.objects.get(pk = pk)
        post.delete()
        return redirect('blog:list')
        
            
    # 클래스 자체에 아예 접근하지 못하게 mixin 필요
    # 로그인이 되었을 때만 삭제 버튼이 보이게.

class DetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
            context = super(DetailView, self).get_context_data()
            context['categories'] = Category.objects.all()
            context['no_category_post_count'] = Post.objects.filter(category=None).count()

            # Post와 연결된 Comment와 HashTag 가져오기
            post = context['post']
            context['comments'] = Comment.objects.filter(post=post)
            context['hashtags'] = HashTag.objects.filter(post=post)

            # 댓글 폼과 해시태그 폼 추가
            context['comment_form'] = CommentForm()
            context['hashtag_form'] = HashTagForm()
            
            return context


# class DetailView(View):
#     def get(self, request, pk): # pk: 디비 post_id, 포스트의 아이디값

#         # list -> object 상세 페이지 -> 상세  페이지 하나의 내용
#         # pk 값을 왔다갔다, 하나의 인자

#         # 데이터베이스 방문
#         # 해당 글 
#         post = Post.objects.get(pk=pk)

#         # 댓글
#         # all - 테이블 전체
#         # get - 값 하나
#         # filter - 조건에 맞는 값
#         comments = Comment.objects.filter(post=post)

#         # HashTag
#         hashtags = HashTag.objects.filter(post=post)

#         # 댓글 폼
#         comment_form = CommentForm()

#         # 해시태그 폼 
#         hashtag_form = HashTagForm()

#         context = {
#             'title': 'Blog',
#             'post': post,
#             'comments': comments,
#             'hashtags': hashtags,
#             'comment_form': comment_form,
#             'hashtag_form': hashtag_form,
#         }

#         return render(request, 'blog/post_detail.html', context)


class commentWrite(LoginRequiredMixin, View): # 일반 뷰를 상속
    # 어차피 디테일 페이지에 달릴 것이므로 특정 페이지를 요청하는 get은 불필요
    # def get(self, request):
    #     pass

    def post(self, request, pk):
        form = CommentForm(request.POST)
        
        # 해당 아이디에 해당하는 글을 불러옴.
        post = Post.objects.get(pk=pk)
        
        if form.is_valid():
            # 사용자에게 댓글 내용을 받아옴
            content = form.cleaned_data['content']
            
            # 유저 정보 가져오기
            writer = request.user

            # 댓글 객체 생성
            comment = Comment.objects.create(post=post, content=content, writer=writer)
            # comment = Comment(post=post).save() 해도 동일하다.
            # redirect은 단순히 이동만 시켜준다. 주소만 옮겨준다. render랑은 다르다.
            # Detail에서 렌더링 처리를 해주는 과정이 추가로 필요하다.
        
            return redirect('blog:detail', pk=pk)

        # 폼이 유효하지 않은 경우에 대한 예외처리
        # form.add_error('폼이 유효하지 않습니다.')
        form.add_error(None, '폼이 유효하지 않습니다.')
        context = {
            'title': 'Blog',
            'post': post,
            'comments': comment,
            'comment_form': form,
        }
        return render(request, 'blog/post_detail.html', context)


class CommentDelete(View):
    def post(self, request, pk): 
        comment = Comment.objects.get(pk=pk)
        post_id = comment.post.id
        comment.delete()

        return redirect('blog:detail', pk=post_id)
    

class HashTagWrite(LoginRequiredMixin, View):
    def post(self, request, pk):
        form = HashTagForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            writer = request.user
            post = Post.objects.get(pk=pk)
            Hashtag = HashTag.objects.create(post=post, name=name, writer=writer)
            return redirect('blog:detail', pk=pk)
    
        form.add_error(None, 'Invalid form.')
        comment_form = CommentForm()
        context = {
            'title': 'Blog',
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': comment_form,
            'hashtag_form': form,
        }
        return render(request, 'blog/post_detail.html', context)
    

class HashTagDelete(View):
    def post(self, request, pk):
        hashtag = HashTag.objects.get(pk=pk)
        post_id = hashtag.post.id
        hashtag.delete()

        return redirect('blog:detail', pk=post_id)
    

class PostSearch(Index):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
        ).distinct()
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'검색결과: {q} ({self.get_queryset().count()})'
        return context
    

blog/templates/blog/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/3b9c96df05.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css.map" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <link href="{% static 'css/styles2.css' %}" rel="stylesheet" media="screen"/>
    
    <title>블로그</title>
</head>
<body>

{% include 'navbar.html' %}
{% include 'footer.html' %}

<div class="container my-5">
    <div class="row">

        <div class="col-md-8 col-lg-9" id="main area">
            <h1 id="post_list-h1" class="mt-3">게시글
                {% if category %}
                    <span class="badge badge-secondary">{{ category }}</span>
                {% endif %}
            </h1><br>
                {% block content %}
                {% endblock %}
        </div>

        {% include 'sc_and_ct.html' %}

    </div>
</div>

{% comment %} <script defer src="list_search.js"></script> {% endcomment %}

    <script>
        function searchPost(){
            let searchValue = document.getElementById('search-input').value.trim();
            if (searchValue.length > 1){
                location.href="/blog/search/" + searchValue + "/";
            }
            else{
                alert('검색어('+ searchValue +')가 너무 짧습니다.');
            }
        };

        document.getElementById('search-input').addEventListener('keyup', function(event){
            if(event.key === 'Enter'){
                searchPost();
            }
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 id="post_detail-title">{{ post.title }}</h2>
            <h3 id="post_detail-writer">By {{ post.writer }}</h3>
            <hr>
            {% if post.category %}
                <span class="badge badge-secondary float-right">{{ post.category }}</span>
            {% else %}
                <span class="badge badge-secondary float-right">미분류</span>
            {% endif %}
            <h5 id="post_detail-created_at">Posted on {{ post.created_at }}</h5>
            <hr>

            <!-- post_list에서 post에 대한 검증을 if 문으로 하고 오기 떄문에 추가 검증은 불필요 -->
            <p class="mt-4"><label for="post-content">내용 </label></p>

            {% if post.file_upload %}
                <label id="uploaded_file">첨부파일: </label>
                <a class="btn btn-primary" href="{{ post.file_upload.url }}" role="button" download>
                    {% if post.get_file_ext == 'csv' %}
                        <i class="fas fa-file-csv"></i>
                    {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                        <i class="fas fa-file-excel"></i>
                    {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                        <i class="fas fa-file-word"></i>
                    {% else %}
                        <i class="far fa-file"></i>
                    {% endif %}

                    {{ post.get_file_name }}
                </a>
            {% endif %}

            {% if post.head_image %}
                <p><img id="post_detail-person" class="card-img-top mt-3" src="{{ post.head_image.url }}" alt="{{ post.title }} head image"></p>
            {% else %}
                {% comment %} <p><img id="post_detail-person" class="card-img-top" src="https://picsum.photos/seed/{{ post.id }}/10/7" alt="random_image"></p> {% endcomment %}
                <p>사진없음</p>
            {% endif %}
            
            <p id="post_detail-content">{{ post.content }}</p>
            <hr>
            <br>

            <!-- 댓글 작성을 위한 기본 폼은 계속 있어야 한다. --> 
            <h3>댓글</h3>
            <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
                {% csrf_token %}
                {{ comment_form.content }}
                <input type="submit" value="댓글 작성">
            </form>

            <!-- if 조건문으로 한번 거르고 값이 있으면, -->
            {% if comments %}
            <!-- 댓글 for 문 -->
                <ul>
                    {% for comment in comments %}
                        <!-- 댓 내용, 작성시간, 삭제버튼 -->
                        <li> 
                            <div class="d-inline">
                            {{ comment.content }} / {{ comment.created_at }} 
                            <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <input type="submit" value="X" class="btn">
                            </form>
                        </li>
                    {% endfor %}
                </ul>
                <br>

            {% else %}
                <p>댓글이 없습니다.</p>
            {% endif %}
            <hr>
            <br>

            <!-- 태그 작성 화면 -->
            <h3>해시태그</h3>
            <form action="{% url 'blog:ht-write' pk=post.pk %}" method="post">
                {% csrf_token %}
                {{ hashtag_form.name }}
                <input type="submit" value="해시태그 작성">
            </form>

            <!-- hashtags -->
            <!-- if 조건문으로 한번 거르고 값이 있으면, -->
            {% if hashtags %}
            <!-- 댓글 for 문 -->
            <ul>
                {% for hashtag in hashtags %}
                    <li>
                        <div class="d-inline">
                        {{ hashtag }}
                        <form action="{% url 'blog:ht-delete' pk=hashtag.pk %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="submit" value="X" class="btn">
                        </form>
                    </li>
                {% endfor %}
            </ul>
            <br>
            <hr>

            {% else %}
                <p> 해시태그가 없습니다. </p><hr>
            {% endif %}
            <br>

            <!-- urls.py에서 글 수정하는 path의 name --> 
            {% if user.is_authenticated and post.writer|lower == request.user|lower %}
                <a href="{% url 'blog:list' %}" class="btn">목록으로</a>
                <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">게시글 수정</a>
                <form action="{% url 'blog:delete' pk=post.pk %}" method="post" class="btn"> <!-- 메소드는 거의 http에서 get아니면 post다. -->
                    {% csrf_token %}
                    <input type="submit" value="게시글 삭제"> <!-- 해놓고 urls.py 수정 필요-->
                </form>
                
            {% else %}
                <!-- {{ post.writer }} / {{ request.user }}<br> -->
                <a href="{% url 'blog:list' %}" class="btn">목록으로</a>
            {% endif %}


        </div>

    </div>
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>블로그 글 수정 화면</h1>

    <!-- 제네릭뷰 -->
    <!-- form은 csrf token, submit이 필수. -->
    <form action="{% url 'blog:edit' pk=post.pk %}" method="post"> <!-- 수정페이지니까 메소드는 포스트 --> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='수정' class="btn btn-outline-success">
    </form>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 id="post_form-write">블로그 글 작성 화면</h1>

    <form action="{% url 'blog:write' %}" method="post" class="mt-4"> <!-- action에 주소 -->
        {% csrf_token %}  <!-- form 요청을 허락하겠다는 명시 -->

        {{ form.as_p }}
        
        {% comment %} <p><label for="id_title">제목: </label><input type="text" name="title" id="id_title"></p>
        <p><label for="id_content">내용: </label><textarea name="content" id="id_content"></textarea></p>
        <p><label for="id_content">사진첨부: </label><a class="btn btn-primary" href="{{ post.head_image.url }}" role="button" download></a></p>
        <p><label for="id_content">파일업로드: </label><a class="btn btn-primary" href="{{ post.file_upload.url }}" role="button" upload></a></p> {% endcomment %}

        <!-- 서버에 값을 넘겨주기 위해 인풋을 사용 -->
        <input type="submit" value="등록" class="btn btn-outline-success">
    </form>

{% endblock %}

<!-- 페이지만 만들었다. view 안 만들었다. -->

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

    <!-- <h1>블로그 게시판 화면</h1> -->
    {% if user.is_authenticated %}
        <p id="post_list-welcome"><b>[{{ user.nickname }}]</b> 님 환영합니다, 블로그 게시판 메인 화면입니다.</p>
        <a id="post_list-write" href="{% url 'blog:write' %}" class="btn mt-3">글쓰기</a>
        {% comment %} <a id="post_list-gohome" href="{% url 'main' %}" class="btn">홈으로</a> {% endcomment %}
    {% else %}
        <p id="not-auth" class=""><b>[등록되지 않은 사용자]</b>입니다. 서비스 이용을 위해 로그인해주시기 바랍니다.</p>
    {% endif %}

    <!-- 글이 있을 때 테이블, 없을 때 특정문구 출력 -->
    <!-- 테이블 안에 티헤드, 티바디 --> 
    {% comment %} 일반 view 상속 시, {% if posts %} {% endcomment %}
    {% if post_list %}
        <table class="table mt-4">
            <thead>
                <tr class="centered1 font1">
                    <th>인물</th>
                    <th>제목</th>
                    <th>내용</th>
                    <th>글쓴이</th>
                    <th>작성날짜</th>
                </tr>
            </thead>
            <tbody>
                {% comment %} 일반 view 상속 시, {% for post in posts %} {% endcomment %}
                {% for post in post_list %}
                <div>

                    <tr class="centered2">
                        
                        <td>
                        {% if post.head_image %}
                            <img id="post_list-person" class="card-img-top" src="{{ post.head_image.url }}" alt="{{ post }} head image">
                        {% else %}
                            {% comment %} <img class="card-img-top" src="https://picsum.photos/seed/{{ post.id }}/10/7" alt="random_image"> {% endcomment %}
                            사진없음
                        {% endif %}
                        </td>

                        <!-- 'blog:detail blog: app_name, detail: urls.py에서의 name --> 
                        <td>
                            <a href="{% url 'blog:detail' pk=post.pk %}" class="btn">
                                {{ post.title | truncatewords:3 }}
                                <!-- comment 갯수 타이틀 옆에 표기 -->
                                {% if post.comment_set.count > 0 %}
                                <span class="text-danger small ml-2">
                                    {{ post.comment_set.count }}
                                </span>
                                {% endif %}
                            </a>
                        </td>
                        <td>{{ post.content | truncatewords:5 }}</td>

                        {% if user.nickname and post.writer|lower == request.user|lower %}
                            <td>{{ user.nickname | truncatewords:1 }}</td>
                        {% else %}
                            <td>{{ post.writer | truncatewords:1 }}</td>
                        {% endif %}

                        <td>{{ post.created_at | truncatewords:1 }}</td>
                    </tr>

                </div>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p id="no-list">작성된 게시물이 없습니다.</p>
    {% endif %}

    {% if is_paginated %}
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; 이전글</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&larr; 이전글</a>
                </li>
            {% endif %}

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_previous_number }}">최신글 &rarr;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">최신글 &rarr;</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

blog/templates/blog/search_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Blog
        {% if search_info %}<small class="text-muted">{{ search_info }}</small>{% endif %}
    </h1>
{% endblock %}