app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexMain.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
# from blog.views import Index

app_name = 'blog'

urlpatterns = [
    path("", views.Index.as_view(), name='list'),

    # 글 상세조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'),
    
    # 글 작성
    path("write/", views.Write.as_view(), name='write'), # views에 write 함수.

    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),

    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),

    # 댓글 작성
    path("detail/<int:pk>/comment/write/", views.commentWrite.as_view(), name='cm-write'),

    # 댓글 삭제
    path("detail/<int:pk>/comment/delete/", views.CommentDelete.as_view(), name='cm-delete'),

    # 해시태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='ht-write'),

    # 해시태그 삭제
    path("detail/<int:pk>/hashtag/delete", views.HashTagDelete.as_view(), name='ht-delete'),

    # 글 검색
    path("search/<str:q>/", views.PostSearch.as_view(), name='search'),

    # 카테고리 검색
    path("category/<str:slug>/", views.CategorySearch, name='category'),

]

# 여기에 정의하는 애들은 서버주소/blog에 정의가 되는 애들이다.

# 함수기반, 클래스기반 뷰의 표기 바업ㅂ이 다르다.
# 캡슐화, 상속 가능.

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

# 여기서는 폼이 아니라 동작할 views.py의 동작할 함수를 받아와야 한다.
urlpatterns = [
    # 회원가입
    path("register/", views.Registration.as_view(), name='register'),

    # 로그인
    path("login/", views.Login.as_view(), name='login'),

    # 로그아웃
    path("logout/", views.Logout.as_view(), name='logout'),

]

blog/models.py
# Create your models here.
from django.db import models
import os

# Create your models here.
# 데이터베이스가 테이블처럼 형태를 가지고 있다.

# 장고에서는 관계형 데이터베이스를 사용한다
# 테이블이나 엑셀 형태를 가지고 있는 것들.

# 장고 블로그를 만들 때 데이터베이스를 만들어야
# 된다고 하면,
# ORM? 데이터베이스를 구축해야 되는 걸 도와주는 것.
# 각각을 클래스로 만들면 알아서 대응되는 
# 테이블을 만들어준다.
# 1:1 대응하는 테이블을 디비에서 만들어준다.
# 이것을 장고의 Orm 기능이라고 한다.


# 클래스 하나가 테이블 하나를 나타낸다.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    # 생성된 시간만 저장을 한다.
    # 크리에이티드엣은 수정이 되면 안되는 시간 값.
    created_at = models.DateTimeField(auto_now_add=True)
    # 새로 세이브 될 때마다 그 시간을 저장을 해준다.
    updated_at = models.DateTimeField(auto_now=True)

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/images/%Y/%m/%d/', blank=True)

    category = models.ForeignKey('Category', blank=True, null=True, on_delete=models.SET_NULL)
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.CharField(max_length=128)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


# class HashTag(models.Model):
#     post = models.ForeignKey('Post', on_delete=models.CASCADE)
#     writer = models.CharField(max_length=128)
#     name = models.CharField(max_length=10)

#     def __str__(self):
#         return self.name

class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.CharField(max_length=128)
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css.map" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <link href="{% static 'css/styles2.css' %}" rel="stylesheet" media="screen"/>
    
    <title>
        {% comment %} {% block title %}
            {{ title }}
        {% endblock %} {% endcomment %}
        Django
    </title>
</head>
<body>

{% include 'navbar.html' %}

<section>
    <div class="container mt-5">
        <div class="row justify-content-between">
            <h1 class="mt-5" id="main-explain">당신을 위한 휴식공간</h1>
            <p class="mt-2" id="main-explain2">일상에 지친 당신, 그리고 우리 모두에게 휴식과 안정이 될만한 좋은 글을 공유하는 공간입니다. 함께 공유해요!</p>
            <br>
            {% comment %} {% block content %}
            {% endblock %} {% endcomment %}
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h2 class="text-light mt-5"><b>Blog - 최신 포스팅</b></h2>
                
                    <div class="card mt-2">
                        <div class="card-body">
                            <h6><a href="/blog/detail/6/" class="text-decoration-none text-dark">최신 게시글1 타이틀(댓글갯수)</a></h6>
                            <span class="badge badge-pill badge-light float-right text-dark">
                            <img class="mr-2 rounded-circle" width="20px" src="" alt="person1">
                                게시글 작성자
                                &nbsp;
                                &nbsp;
                                내용
                                &nbsp;
                                &nbsp;
                                작성일
                            </span>
                        </div>
                    </div>
                
                    <div class="card mt-2">
                        <div class="card-body">
                            <h6><a href="/blog/5/" class="text-decoration-none text-dark">인프런에 동영상 강좌가 등록되었습니다.</a></h6>
                            <span class="badge badge-pill badge-light float-right">
                                <img class="mr-1 rounded-circle" width="20px" src="https://lh3.googleusercontent.com/a/AAcHTtd-dXmhDXkgs6U5HPIZ2LkxBtVHM-IZ-xbU6IYLE1bFVbE=s96-c" alt="sungyong">
                                sungyong
                                &nbsp;
                                &nbsp;
                                June 23, 2021, 11:16 a.m.
                            </span>
                        </div>
                    </div>
                
                    <div class="card mt-2">
                        <div class="card-body">
                            <h6><a href="/blog/4/" class="text-decoration-none text-dark">cryptography 오류시 대처법</a></h6>
                            <span class="badge badge-pill badge-light float-right">
                                <img class="mr-1 rounded-circle" width="20px" src="https://lh3.googleusercontent.com/a-/AOh14Gj4bqungfeMpjW_3BpKCYrSGsG01jcDYKUzCnjA=s96-c" alt="taegon">
                                taegon
                                &nbsp;
                                &nbsp;
                                May 10, 2021, 4:50 p.m.
                            </span>
                        </div>
                    </div>
                
                    <div class="card mt-2">
                        <div class="card-body">
                            <h6><a href="/blog/6/" class="text-decoration-none text-dark">StartBootstrap 버전 문제</a></h6>
                            <span class="badge badge-pill badge-light float-right">
                                <img class="mr-1 rounded-circle" width="20px" src="https://lh3.googleusercontent.com/a/AAcHTtd-dXmhDXkgs6U5HPIZ2LkxBtVHM-IZ-xbU6IYLE1bFVbE=s96-c" alt="sungyong">
                                sungyong
                                &nbsp;
                                &nbsp;
                                June 30, 2021, 1:12 a.m.
                            </span>
                        </div>
                    </div>

                    <div class="card mt-2">
                        <div class="card-body">
                            <h6><a href="/blog/6/" class="text-decoration-none text-dark">StartBootstrap 버전 문제</a></h6>
                            <span class="badge badge-pill badge-light float-right">
                                <img class="mr-1 rounded-circle" width="20px" src="https://lh3.googleusercontent.com/a/AAcHTtd-dXmhDXkgs6U5HPIZ2LkxBtVHM-IZ-xbU6IYLE1bFVbE=s96-c" alt="sungyong">
                                sungyong
                                &nbsp;
                                &nbsp;
                                June 30, 2021, 1:12 a.m.
                            </span>
                        </div>
                    </div>

            </div>
        </div>
    </div>
</section>

{% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    {% comment %} <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> {% endcomment %}
</body>
</html>

<!-- 수정 필요 -->

templates/footer.html
<div class="fixed-bottom">
    <!-- Footer -->
<footer class="py-3 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white" id="footer-word">
            Copyright &copy; 좋은 글과 함께 마음의 휴식을.
        </p>
    </div>
    <!-- /.container -->
</footer>

</div>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    {% comment %} <h1>index.html</h1>
    <br> {% endcomment %}

    {% if user.is_authenticated %}
    <p>"{{ user.email }}", welcome to visit this blog! you can do anything what you want in this blog. try it!!</p>
    <br>
    <a href="{% url 'blog:list' %}">블로그 입장하기</a>
    <br><br>
    <a href="{% url 'user:register' %}">회원가입</a>
    <br><br>
    <a href="{% url 'user:logout' %}">로그아웃</a>
    
    {% else %}
    <p>please login, "anonymous" user!</p>
    <br>
    <a href="{% url 'blog:list' %}">블로그 입장하기</a>
    <br><br>
    <a href="{% url 'user:register' %}">회원가입</a>
    <br><br>
    <a href="{% url 'user:login' %}">로그인</a>

    {% endif %}

    {% comment %} <p>회원가입</p>
    <p>로그인</p> {% endcomment %}

{% endblock %}

templates/navbar.html
<nav id="navibar" class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        
            <a class="navbar-brand" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blog:list' %}">Blog</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:register' %}" data-toggle="modal" data-target="#registerModal">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}" data-toggle="modal" data-target="#loginModal">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}" data-toggle="modal" data-target="#logoutModal">Logout</a>
                    </li>
                </ul>
            </div>
        
    </div>
</nav>

templates/sc_and_ct.html
<div class="col-md-4 col-lg-3">
    <!-- Search Widget -->
    <div class="card my-4">
        <h2 id="post_list-search" class="card-header">검색</h2>
        <div class="card-body">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." id="search-input">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="button" onclick="searchPost();">찾기</button>
                </span>
            </div>
        </div>
    </div>

    <!-- category widget -->
    <div class="card my-4" id="categories-card">
        <h2 id="post_list-category" class="card-header">카테고리</h2>
        <div class="card-body">
            <div class="row">

                <ul>
                    {% for category in categories %}
                    <li id="category-list">
                        <a id="category-elem1" href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                    </li>
                    {% endfor %}
                    <li id="category-list">
                        <a id="category-elem2" href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                    </li>
                </ul>

            </div>
        </div>
    </div>

</div>